tas2580_regcheck_username:
    pattern: /regcheck/username.html
    defaults: { _controller: tas2580.regcheck.main:username }
tas2580_regcheck_password:
    pattern: /regcheck/password.html
    defaults: { _controller: tas2580.regcheck.main:password }
tas2580_regcheck_email:
    pattern: /regcheck/email.html
    defaults: { _controller: tas2580.regcheck.main:email }