tas2580_regcheck_username:
    pattern: /username
    defaults: { _controller: tas2580.regcheck.main:username }
tas2580_regcheck_password:
    pattern: /password
    defaults: { _controller: tas2580.regcheck.main:password }
tas2580_regcheck_email:
    pattern: /email
    defaults: { _controller: tas2580.regcheck.main:email }